version: '3.3'

services:
  potty_api:
    build: .
    image: potty_nest
    container_name: potty_api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/usr/src/vuttr/logs:rw
      - ./src:/usr/src/vuttr/src
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - potty-db
  potty-db:
    image: postgres
    container_name: 'potty-db'
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=$TYPEORM_USERNAME
      - POSTGRES_PASSWORD=$TYPEORM_PASSWORD
      - TYPEORM_USERNAME=$TYPEORM_USERNAME
      - TYPEORM_PASSWORD=$TYPEORM_PASSWORD
      - TYPEORM_DATABASE=$TYPEORM_DATABASE
    ports:
      - '5433:5432'

  potty_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      potty_EMAIL: admin@admin.com
#      potty_PASSWORD: root
#    ports:
#      - "5050:80"

volumes:
  api-logs:
  db: