
name: Build and run tests

on:
  push:
    branches: [ staging, dev ]
  pull_request:
    branches: [ staging, dev ]

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: 16
#         cache: 'yarn'
#     - run: yarn install
#     - run: yarn build
    # - run: npm test

  deploy_dev:
    if: contains( github.ref, 'dev')
    runs-on: ubuntu-latest
#     needs: build
    environment: dev
    env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        HOSTNAME : ${{ secrets.HOSTNAME  }}
        USER_NAME : ${{ secrets.USER_NAME  }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: 'echo "$PRIVATE_KEY" >> ~/.ssh/github-action'
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host bdv\n\tUser ${USER_NAME}\n\tHostname ${HOSTNAME}\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config       
      
      - name: Deploy with rsync
        run: rsync -e ssh /home/runner/work/potty-api/potty-api/dist bdv:/var/www/potty-api/dist/
        
      - name: build pm2
        run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} uptime
      - run: |
          ssh -i private_key ${USER_NAME}@${HOSTNAME} '
          cd /var/www/potty-api &&
          git pull origin dev &&
          export NODE_OPTIONS="--max-old-space-size=4096" &&
          npm i &&
          pm2 delete potty-api &&
          pm2 start dist/main.js --name "potty-api"
          '
